services:
  postgres:
    image: postgres
    container_name: postgres_db_container
    environment:
      - POSTGRES_DB=${POSTGRES_DB}
      - POSTGRES_USER=${POSTGRES_USER}
      - POSTGRES_PASSWORD=${POSTGRES_PASSWORD}
    ports:
      - "5432:5432"
    restart: unless-stopped
    volumes:
      - postgres_data:/var/lib/postgresql/data
      
  backend:
    build:
      context: ./backend
    container_name: backend_container
    environment:
      - PORT=3000
      - DATABASE_URL=${DATABASE_URL}
    ports:
      - "3000:3000"
    depends_on:
      - postgres
    restart: unless-stopped

  frontend:
    build:
      context: ./frontend
    container_name: frontend_container
    environment:
      - PORT=5173
      - VITE_BACKEND_URL=${VITE_BACKEND_URL}
    ports:
      - "5173:5173"
    depends_on:
      - backend
    restart: unless-stopped

volumes:
  postgres_data: