services:
  postgres:
    image: postgres
    container_name: postgres_db_container
    environment:
      - POSTGRES_DB=${POSTGRES_DB}
      - POSTGRES_USER=${POSTGRES_USER}
      - POSTGRES_PASSWORD=${POSTGRES_PASSWORD}
    ports:
      - "5432:5432"
    restart: unless-stopped
  backend:
    build:
      context: ./backend
    container_name: backend_container
    environment:
      - DATABASE_URL=${DATABASE_URL}
      - PORT=3001
    ports:
      - "3001:3001"
    depends_on:
      - postgres
    restart: unless-stopped

  frontend:
    build:
      context: ./frontend
    container_name: frontend_container
    environment:
      - VITE_BACKEND_URL=backend:3001/api
      - PORT=5173
    ports:
      - "5173:5173"
    depends_on:
      - backend
    restart: unless-stopped